# {model}_[model setting]_{backbone}_{neck}_[norm setting]_[misc]_[gpu x batch_per_gpu]_{schedule}_{dataset}

_BASE_: "../Base-RetinaNet.yaml"

MODEL:
  # WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  WEIGHTS: "pretrained_models/retina_R101_3x/model_final_971ab9.pkl"
  RESNETS:
    DEPTH: 101
  BACKBONE:
    FREEZE_AT: 3  # NOTE: default 2
  RETINANET:
    NUM_CLASSES: 8

SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.001

  REL_STEPS: (0.78, 0.93)
  TOTAL_EPOCHS: 8

DATASETS:
  TRAIN: ("lmo_pbr_train",)
  TEST: ("lmo_bop_test",)

INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  # MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
  COLOR_AUG_ON: True
  COLOR_AUG_TYPE: "CODE"
  COLOR_AUG_CODE: |
    Sequential([
      Sometimes(0.4, CoarseDropout( p=0.1, size_percent=0.05) ),
      # Sometimes(0.5, Affine(scale=(1.0, 1.2))),
      Sometimes(0.5, GaussianBlur(np.random.rand())),
      Sometimes(0.5, Add((-20, 20), per_channel=0.3)),
      Sometimes(0.4, Invert(0.20, per_channel=True)),
      Sometimes(0.5, Multiply((0.7, 1.4), per_channel=0.8)),
      Sometimes(0.5, Multiply((0.7, 1.4))),
      Sometimes(0.5, ContrastNormalization((0.5, 2.0), per_channel=0.3))],
    random_order=False)
    # aae weaker

OUTPUT_DIR: "output/bop_det/lmo/retina_R101_FPN_MSx1333_ColorAugAAEWeaker_8e_lmo_pbr/"
